name: Linting

on: [push, pull_request]

jobs:
  ruff-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.10
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.12.0
    - name: Run ruff linter
      run: |
        ruff check

  ruff-formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.10
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.12.0
    - name: Run ruff formatter
      run: |
        ruff format --check

